services:
  ainz:
    build:
      context: .
    image: trellisfw/ainz
    restart: unless-stopped
    #volumes:
    # Additional template helpers can be mapped into the helpers dir.
    # Ainz will load all helpers it finds at boot.
    #- ./path/to/helper-module:/trellis/ainz/dist/helpers/helper-module
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED
      - NODE_ENV=${NODE_ENV:-development}
      - DEBUG=${DEBUG-*:error,*:warn,*:info}
      # Connect to host if DOMAIN not set?
      # You should really not rely on this though. Set DOMAIN.
      - domain=${DOMAIN:-host.docker.internal}
      # TODO: Nicer way to deal with tokens?
      - token=${AINZ_TOKENS:-god}
